const categories = {
    "Identity": [ //15
        "What is your first name?",
        "What is your middle name?",
        "How old are you?",
        "When is your birthday?",
        "What is your sexual orientation?",
        "What color is your hair?",
        "What are you wearing right now?",
        "What is your general clothing style?",
        "What is your zodiac sign?",
        "Do you have any tatoos or piercings?",
        "What is your relationship status?",
        "Where do you fall on the introvert/extrovert spectrum?",
        "What is your eye color?",
        "How many siblings do you have?",
        "Do you have any pets?",
    ],
    "Preferences": [ //20
        "What is your favorite movie?",
        "What is your favorite food?",
        "What is a food you can't stand?",
        "What are you currently listening to?",
        "What is your favorite season and why?",
        "Do you have a favorite sports team?",
        "What is your favorite video game?",
        "If you drink alcohol, what is your favorite drink?",
        "What is your favorite animal?",
        "Pepsi, Dr pepper or coke?",
        "Describe your ideal game or movie",
        "What is your favourite commercial chocolate?",
        "What is your favourite dessert?",
        "What is your perfect date?",
        "What is the ideal christmas gift to get you?",
        "What is your favourite way to escape stress?",
        "What are you deathly scared of?",
        "What type of horror scares you most effectively?",
        "Favourite academic subject?",
        "What is your favourite junk/fast food?"
    ],
    "Life": [ //15
        "What are your career goals?",
        "What is the hardest challenge you've faced in life?",
        "How many relationships have you had?",
        "Do you have a lot of friends?",
        "What is your greatest social skill?",
        "What are your hobbies?",
        "What is a skill not many people know you have?",
        "What is your favorite memory?",
        "What is your most embarrassing moment?",
        "What is your dream vacation?",
        "What is your dream career?",
        "What is your dream home like?",
        "Would you get married?",
        "Do you want kids?",
        "Have you ever done a thrillseeking activity? (skydiving etc)",
    ],
    "Lifestyle" : [ //10
        "Are you a nightowl?",
        "Party life or quiet time?",
        "Do you prefer hot or cold room temp?",
        "Do you subscribe to a particular diet?",
        "Do you prefer to plan stuff or wing it?",
        "Do you have a big social battery?",
        "Best movie experience? Quiet night in vs Cinema",
        "What is your depresso day coping mechanism?",
        "What is your typical evening like?",
        "When is the best time to shower?",
    ],
    "Reddit": [ //6
        "What is your favorite subreddit?",
        "What subreddit do you love but wouldn't ever admit to it?",
        "How much time per day do you spend on reddit?",
        "Do you follow any NSFW subreddits?",
        "What would happen if your irl friends could see your reddit history?",
        "If you could make a subreddit about anything, what would it be?",
    ],
    "Hypothetical": [ //16
        "What would you choose as your superpower?",
        "What would be the worst superpower to have?",
        "What would be your three wishes to a Genie?",
        "$50 a day for the rest of your life or $200,000 right now?",
        "If you could be invisible for a day, what would you do?",
        "What is your plan for the zombie apocalypse?",
        "What is your plan for the alien invasion?",
        "You have 2 weeks to live in a game to accomplish a random task, which game do you choose?",
        "What would you do if you won the lottery?",
        "Which 5 items would you take to a desert island?",
        "If you could have a time machine, when would you go to?",
        "If we swapped bodies for 24 hours, what would you do?",
        "What movie/game/show situation would you be terrified to be in?",
        "Deep sea mission or orbital space mission?",
        "You're given a budget of $100m to solve world hunger, what's your plan?",
        "You have to take me on a weekend getaway, where would you take me?",
    ],
    "NSFW": [ //24
        "Are you a virgin?",
        "Have you ever given oral?",
        "What is your body count?",
        "Do you shave?",
        "Kissing during sex?",
        "You have to fuck the person you're doing this chart with, which position do you choose?",
        "What is the most amount of times you've masturbated in one day?",
        "How big is your dick/How big are your boobs?",
        "Are you submissive, dominant or a switch?",
        "Uno reverse! Pick any number from the list and ask it",
        "How often do you get horny?",
        "What is something unexpected someone would learn from fucking you?",
        "Do you masturbate? How often?",
        "What are your favourite sex positions?",
        "Which is better, spitting or swallowing?",
        "What simple/innocent thing never fails to turn you on?",
        "When did you last masturbate?",
        "Best place to cum?",
        "What happened in your last sex dream?",
        "Have you ever gotten handjob/been fingered?",
        "What is a secret kink no one knows you have?",
        "What is the weirdest place you've masturbated?",
        "Do you prefer rough or gentle sex?",
        "Sexually speaking, What is your absolute weakness?",
    ],
}
